import { NextResponse } from 'next/server'
import * as XLSX from 'xlsx'
import { getSessionUser } from '@/lib/auth'
import { fmtDateTime, istToday } from '@/lib/dates'
import {
  aggregateEmployees,
  aggregateKpis,
  buildOptions,
  filterRows,
  filterUsers,
  getReportScope,
  loadReportRows,
  parseFilterParams,
} from '@/lib/reports'

/**
 * GET /api/reports/export — detailed Excel report (3 sheets: Summary,
 * Employee Performance, Task Details) for the visible downline, honoring
 * the same filters as /api/reports.
 */
export async function GET(req: Request) {
  const session = await getSessionUser()
  if (!session) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })

  const scope = await getReportScope(session)
  if (!scope || scope.users.length === 0) {
    return NextResponse.json({ error: 'You do not have any team members reporting to you' }, { status: 403 })
  }

  const filters = parseFilterParams(new URL(req.url).searchParams)
  const allRows = await loadReportRows(scope.users)
  const filtered = filterRows(allRows, filters)
  const scopeUsers = filterUsers(scope.users, filters)
  const kpis = aggregateKpis(filtered, scopeUsers.length)
  const byEmployee = aggregateEmployees(filtered, scopeUsers)
  const options = buildOptions(scope.users, allRows, session)

  const wb = XLSX.utils.book_new()

  const labelFor = (opts: { value: string; label: string }[], values: string[]) => {
    if (!values.length) return 'All'
    if (values.includes('__NONE__')) return 'None'
    return values
      .map((v) => opts.find((o) => o.value === v)?.label ?? v)
      .join(', ')
  }
  const plainList = (values: string[]) => {
    if (!values.length) return 'All'
    if (values.includes('__NONE__')) return 'None'
    return values.join(', ')
  }

  // ── Sheet 1: Summary ────────────────────────────────────────────
  const filtersApplied: [string, string][] = [
    ['Month (due date)', labelFor(options.months, filters.months)],
    ['Process', plainList(filters.processes)],
    ['Designation', plainList(filters.designations)],
    ['L1 Manager', labelFor(options.managers, filters.managerIds)],
    ['Employee', labelFor(options.employees, filters.userIds)],
  ]
  const summary: (string | number)[][] = [
    ['Digitide TaskFlow — Team Performance Report'],
    [`Generated by ${session.name} (${session.employeeCode})`],
    [`Generated on ${fmtDateTime(new Date())} IST`],
    [`Scope: ${scope.scope === 'org' ? 'Whole organization' : 'Your downline'}`],
    [],
    ['Filters applied'],
    ...filtersApplied,
    [],
    ['Key metrics', 'Value'],
    ['Employees in scope', kpis.employees],
    ['Total assignments', kpis.total],
    ['Completed', kpis.completed],
    ['Completed on time', kpis.onTime],
    ['Completed late', kpis.late],
    ['Pending (on track)', kpis.pending],
    ['In progress (on track)', kpis.inProgress],
    ['Overdue (open, past due)', kpis.overdue],
    ['Aborted', kpis.aborted],
    ['Completion rate %', kpis.completionRate],
    ['On-time delivery rate %', kpis.onTimeRate],
  ]
  const wsSummary = XLSX.utils.aoa_to_sheet(summary)
  wsSummary['!cols'] = [{ wch: 30 }, { wch: 46 }]
  wsSummary['!merges'] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 1 } }]
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary')

  // ── Sheet 2: Employee Performance ───────────────────────────────
  const empHeader = [
    'Employee Code', 'Employee', 'Process', 'Designation', 'L1 Manager',
    'Total', 'Completed', 'On-time', 'Late', 'Pending', 'In Progress',
    'Overdue', 'Aborted', 'Completion %', 'On-time %', 'Avg Delay (days)',
  ]
  const empRows = byEmployee.map((e) => [
    e.employeeCode, e.name, e.process, e.designation, e.managerName ?? '—',
    e.total, e.completed, e.onTime, e.late, e.pending, e.inProgress,
    e.overdue, e.aborted, e.completionRate, e.onTimeRate, e.avgDelayDays,
  ])
  const wsEmp = XLSX.utils.aoa_to_sheet([empHeader, ...empRows])
  wsEmp['!cols'] = [14, 20, 14, 18, 20, 8, 10, 9, 7, 9, 11, 9, 9, 13, 10, 15].map((wch) => ({ wch }))
  if (empRows.length > 0) {
    wsEmp['!autofilter'] = { ref: XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: empRows.length, c: empHeader.length - 1 } }) }
  }
  XLSX.utils.book_append_sheet(wb, wsEmp, 'Employee Performance')

  // ── Sheet 3: Task Details ───────────────────────────────────────
  const detailHeader = [
    'Task', 'Employee', 'Employee Code', 'Process', 'Designation', 'L1 Manager',
    'Assigned By', 'Due Date (IST)', 'Completed On (IST)', 'Status', 'Task State',
    'Overdue', 'Delay (days)',
  ]
  const detailRows = filtered.map((r) => [
    r.title,
    r.userName,
    r.employeeCode,
    r.process,
    r.designation,
    r.managerName ?? '—',
    r.assignedBy,
    fmtDateTime(r.dueDate),
    r.completedAt ? fmtDateTime(r.completedAt) : '—',
    r.aborted ? 'Aborted' : r.status === 'PENDING' ? 'Pending' : r.status === 'IN_PROGRESS' ? 'In Progress' : 'Completed',
    r.aborted ? 'Aborted' : 'Active',
    r.overdue ? 'Yes' : 'No',
    r.delayDays > 0 ? r.delayDays : 0,
  ])
  const wsDetail = XLSX.utils.aoa_to_sheet([detailHeader, ...detailRows])
  wsDetail['!cols'] = [34, 18, 13, 13, 16, 18, 16, 22, 22, 12, 11, 9, 12].map((wch) => ({ wch }))
  if (detailRows.length > 0) {
    wsDetail['!autofilter'] = { ref: XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: detailRows.length, c: detailHeader.length - 1 } }) }
  }
  XLSX.utils.book_append_sheet(wb, wsDetail, 'Task Details')

  const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer
  const filename = `TaskFlow-Report-${istToday()}.xlsx`
  return new NextResponse(new Uint8Array(buf), {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-store',
    },
  })
}
